/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Placement;
import java.sql.*;
import javax.swing.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class ApplicantTable extends javax.swing.JFrame {
public static int i;
public static int z;
public static int run=0;
    /**
     * Creates new form ApplicantTable
     */
    public ApplicantTable() {
        initComponents();
         DefaultTableModel amodel=(DefaultTableModel)jTable1.getModel();
        amodel.setRowCount(0);
        try{
        Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","anchit","123");
        String colhead[]={"Company Name","Vacancies","Salary","Job Title"};
        amodel.setColumnIdentifiers(colhead);
        Statement st= con.createStatement();
        ResultSet rs=st.executeQuery("select * from Applicant");
        while(rs.next())
        {
            if(rs.getString(7).equals(Global.pswdap))
            {
                Global.jbtap=String.valueOf(rs.getString(5));
            }
        }
        String sql="select * from Employer where Job_Title='"+Global.jbtap+"' AND Vacancy>0";
        ResultSet rs1=st.executeQuery(sql);
         ResultSetMetaData rsmd=rs1.getMetaData();
        int cols=rsmd.getColumnCount();
        while(rs1.next())
        {
            Object[] obj=new Object[cols];
            for(int i=0;i<cols;i++)
            {
                obj[i]=rs1.getObject(i+1);
            }
            amodel.addRow(obj);
        }
        } catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"Connection Unsucessful");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Companies");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Company Name", "Vacancies", "Salary", "Job Title"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setToolTipText("");
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        jButton1.setText("Apply for Job");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Check Job Status");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(jButton1)
                .addGap(118, 118, 118)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
        Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","anchit","123");
        Statement st= con.createStatement();
        int r = jTable1.getSelectedRow();
        if (r==-1) {
            JOptionPane.showMessageDialog(this,"Please select a row");
        } else
        {
            java.util.List<String> list = new ArrayList<String>();
            int[] a = jTable1.getSelectedRows();
            z =a.length;
            String[] listId = new String[z+1];
             
            for (i=0; i<z; i++) {
                list.add((String) jTable1.getValueAt(a[i], 0));
            }
            listId = (String[])list.toArray(new String[list.size()]);
            ResultSet rs=st.executeQuery("select * from Applied_Students where Name='"+Global.name+"'");
             while(rs.next()&& Global.run==0)
             {
      
                  for(i=0;i<z;i++)
                {
                    if(rs.getString(8).equals(listId[i]))
                    {
                       JOptionPane.showMessageDialog(this,"Already Applied For Selected Company");
                        Global.run=1;
                        dispose();
                        Login oLogin=new Login();
                        oLogin.setVisible(true);
                        
                    }
                }
             }
             
                 if(Global.run==0)
                    {
                        for(i=0;i<z;i++)
                        {
                        String sql="insert into Applied_Students(Name,Age,Sex,Branch,Job_Title,Applied_For) values('"+Global.name+"',"+Global.age+",'"+Global.sex+"','"+Global.branch+"','"+Global.job_title+"','"+listId[i]+"')";
                        st.executeUpdate(sql);
                        }
                        JOptionPane.showMessageDialog(this,"Applied Successfully");
                        dispose();
                        Login oLogin=new Login();
                        oLogin.setVisible(true);
                    }
                  
         }}catch(Exception e)
        {
          JOptionPane.showMessageDialog(this,"Connection Unsuccessful");
        }
        
            
            
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        OfferedStudents oofferedStudents=new OfferedStudents();
        dispose();
        oofferedStudents.setVisible(true);
        
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicantTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicantTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicantTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicantTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplicantTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
