/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Placement;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.*;
/**
 *
 * @author HP
 */
public class EmployerTable extends javax.swing.JFrame {
public static int z;
public static int i;
    /**
     * Creates new form EmployerTable
     */
    public EmployerTable() {
        initComponents();
         jTextField1.setText(String.valueOf(Global.vacancy));
        DefaultTableModel amodel=(DefaultTableModel)jTable1.getModel();
        amodel.setRowCount(0);
        try{
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","anchit","123");
        String colhead[]={"Name","Age","Sex","Branch","Job Title"};
        amodel.setColumnIdentifiers(colhead);
        Statement st= con.createStatement();
        String sql="select * from Applied_Students where Applied_For='"+Global.empname+"'";
        ResultSet rs1=st.executeQuery(sql);
        ResultSetMetaData rsmd=rs1.getMetaData();
        int cols=rsmd.getColumnCount();
        while(rs1.next())
        {
            
            Object[] obj=new Object[cols];
            for(int i=0;i<cols;i++)
            {
                obj[i]=rs1.getObject(i+1);
            }
            amodel.addRow(obj);
        }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"Connection Unsuccessful");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Applicable Applicants");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Age", "Sex", "Branch", "Job Title"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        jButton1.setText("Offer Positon");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Click Here To Update Vancancy");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Available Vacancies");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(149, 149, 149)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(Global.vacancy>0)
                {
        int r = jTable1.getSelectedRow();
        int s[]=jTable1.getSelectedRows();
        int length=s.length;
        if (r==-1) {
            JOptionPane.showMessageDialog(this,"Please select a row");
        } else if(length<=Global.vacancy)
        {
            java.util.List<String> list = new ArrayList<String>();
            int[] a = jTable1.getSelectedRows();
            z =a.length;
            String[] listId = new String[z+1];
             
            for (i=0; i<z; i++) {
                list.add((String) jTable1.getValueAt(a[i], 0));
            }
            listId = (String[])list.toArray(new String[list.size()]);
            try
            {
              Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","anchit","123");    
             Statement st= con.createStatement();
             ResultSet rs=st.executeQuery("select * from Offered_Students where Offered_By='"+Global.empname+"'");
             while(rs.next()&& Global.running==0)
             {
                       for(i=0;i<z;i++)
                       {
                    if(rs.getString(1).equals(listId[i]))
                    {
                       JOptionPane.showMessageDialog(this,"Already Offered That Candidate");
                        Global.running=1;
                        dispose();
                        Login oLogin=new Login();
                        oLogin.setVisible(true);
                        
                    }
                }
             }
             
                 if(Global.running==0)
                    {
                        for(i=0;i<z;i++)
                        {
                         ResultSet rs1=st.executeQuery("select * from Applied_Students where Applied_For='"+Global.empname+"' AND Name='"+listId[i]+"'");
                         while(rs1.next())
                         {
                             Global.oname=String.valueOf(rs1.getString(1));
                             Global.oage=Integer.parseInt(rs1.getString(2));
                             Global.osex=String.valueOf(rs1.getString(3));
                             Global.obranch=String.valueOf(rs1.getString(4));
                             Global.ojobtitle=String.valueOf(rs1.getString(5));
                         }
                        String sql="insert into Offered_Students values('"+listId[i]+"',"+Global.oage+",'"+Global.osex+"','"+Global.obranch+"','"+Global.ojobtitle+"','"+Global.empname+"')";
                        st.executeUpdate(sql);
                        String sq="update Employer set Vacancy=Vacancy-1 where Name='"+Global.empname+"'";
                        st.executeUpdate(sq);
                        }
                        JOptionPane.showMessageDialog(this,"Offered Successfully");
                        dispose();
                        Login oLogin=new Login();
                        oLogin.setVisible(true);
                    }
                  
           }catch(Exception e)
        {
          JOptionPane.showMessageDialog(this,"Connection Unsuccessful");
        }
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Number of Student Selected Is More Than Vacancy");
        }
                }
                else
                {
                        JOptionPane.showMessageDialog(this,"Increase your vacancy");
                        }
            
        
     // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       /* DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        int selectedRowIndex=jTable1.getSelectedRow();
        JOptionPane.showMessageDialog(this,model.getValueAt(selectedRowIndex,0).toString());
        */
        



        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Update oUpdate=new Update();
        dispose();
        oUpdate.setVisible(true);
         jTextField1.setText(String.valueOf(Global.vacancy));

        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
       
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployerTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployerTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployerTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployerTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployerTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
